### ISSUE TITLE
Embedded update oddness

### ISSUE THREAD

**Issue by nyarly** [LRDesign/relayer#20]
Quick note:

updates on embedded resources should probably simply fail. (currently they succeed, which is confusing) To do such an update:
- modify the embedded resource, and then update() it's parent manually
- load() the resource to get the current canonical version, modify that and update() (but beware skew with the parent)

Ways Relayer could improve on this story:
- Actually fail update() on an embedded resource
- _unless_ the server includes a /meta/etag field, in which case: produce a "blind" PATCH (which requires keeping track of "pristine" versions of responses) and attempt to update with that. Note that added fields may lead to errors here, since the PATCH will say "added this field" when the server might expect "change this field"

(Relayer backends then would add the etag partially by way of advertising the acceptance of PATCH)

**Comment by hannahhoward** [comment]
I'm not sure embedded updates should fail. One of the great goals with relayer is to effectively hide the  user of the library from having to know what's embedded and what's linked. we used this to great benefit in Yoric, by being able to move resources from linked to embedded for optimization without changing the client code. In fact one could argue that's the entire point of hypermedia to begin with. I don't see how this works if the library user has to remember to manually load the canonical version  of the resource in order to update it. So if a canonical resource has to be loaded, it should be done behind the scenes -- within relayer without the library user having to do it manually. Or alternatively apply the patch strategy on the server. Either solution is essentially load the pristine canonical resource and then patch, only difference being one patches in the client, the other patches in the server.

**Comment by nyarly** [comment]
Transfering this issue to XingFramework and continuing discussion there
